spring:
  application:
    name: ag-gate



#配置路由
zuul:
#/api/uc/user/test --> user-center   /user/test   stripPrefix不设置时，不加uc前缀
#/api/uc/user/test --> user-center   /uc/user/test
#/api/admin/user/test   /admin/user/test stripPrefix:false
  prefix: /api #为zuul设置一个公共的前缀 所有请求的前缀  如果routes不p配置就是api/user-center/user/test
  routes:
    uc:
      path: /uc/**
      serviceId: user-center
#      stripPrefix: false  # 设置为false 不移除前缀 uc  就是访问时加uc  #/api/uc/user/test  ----/uc/user/test


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8766

jwt:
  key: xxxxxx1
  expireTime: 3000
  pub-key: path:/Users/ace/git/ag-parent/ag-auth/src/main/resources/client/pub.key
  pri-key: path:/Users/ace/git/ag-parent/ag-auth/src/main/resources/client/pri.key;
                      }