spring:
  application:
    name: admin-gate



#配置路由
zuul:
#/api/uc/user/test --> uc   /user/test   stripPrefix不设置时，不加uc前缀
#/api/uc/user/test --> uc   /uc/user/test
#/api/admin/user/test   /admin/user/test stripPrefix:false
  prefix: /api #为zuul设置一个公共的前缀 所有请求的前缀  如果routes不p配置就是api/uc/user/test
  routes:
    user-center:
      path: /uc/**
      serviceId: user-center #      stripPrefix: false  # 设置为false 不移除前缀 uc  就是访问时加uc  #/api/uc/user/test  ----/uc/user/test
    auth-server:
      path: /auth/**
      serviceId: admin-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8766

jwt:
  token-header:
    jwtTokenHeader: access-token
  ignore-url:
    jwtIgnoreUrl: /auth/jwt
  pub-key:
    path:
      pubKeyPath: D:\syzSpringCloudProject\syz_admin\syz-oauth-study\admin-zuul\src\main\resources\jwt\pub.key

client:
  token-header: client-token
  id: admin-gate
  secret: 123456