spring:
  application:
    name: admin-auth
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/admin_study?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7777


mybatis:
    basepackage: com.syz.security.auth.mapper
    xmlLocation: classpath:mapper/**/*.xml

jwt:
  expireTime: 3000
  pub-key:
    path:
      pubKeyPath: D:\syzSpringCloudProject\syz_admin\syz-oauth-study\admin-auth\src\main\resources\jwt\pub.key
  pri-key:
    path:
      priKeyPath: D:\syzSpringCloudProject\syz_admin\syz-oauth-study\admin-auth\src\main\resources\jwt\pri.key

client:
  expireTime: 3000
  pub-key:
    path:
      pubKeyPath: D:\syzSpringCloudProject\syz_admin\syz-oauth-study\admin-auth\src\main\resources\client\pub.key
  pri-key:
    path:
      priKeyPath: D:\syzSpringCloudProject\syz_admin\syz-oauth-study\admin-auth\src\main\resources\client\pri.key
